on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.check.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: ./.github/actions/check
  issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    needs: [check]
    strategy:
      matrix: ${{fromJson(needs.check.outputs.matrix)}}
    steps:
      - id: create-issue
        run: |
          echo "Create issue for ${{ matrix.file }}"
          existing_issue=$(gh issue list --label "doc-status" --label "fixture/Article.md" --json number --jq '.[0].number')
          if [[ -n $existing_issue ]]; then
            gh issue repoen "$existing_issue" -c "${{ matrix.file }} is outdated again"
          else
            gh label create doc-status --color E99695 -f
            gh label create ${{ matrix.file }} -f
            gh issue create \
              --title "${{ matrix.file }}" \
              --label "doc-status,${{ matrix.file }}" \
              --body "## Article out of date\n[${{ matrix.file }}](./${{ matrix.file }})"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

  push:
    runs-on: ubuntu-latest
    needs: [issue]
    permissions:
      contents: write
    steps:
      - id: push
        run: | 
          git config --global user.name 'Doc-Status'
          git config --global user.email 'doc-status@users.noreply.github.com'
          git commit -am "chore(doc-status): set status"
          git push
